import { Account, DriveItem } from "@/types/index"

export const driveItems: DriveItem[] = [
  // --- Root Level Items (parentId: null) ---
  {
    id: "folder-1",
    name: "🚀 Project Alpha",
    type: "Folders",
    owner: "Alice",
    dateModified: "2025-07-15",
    parentId: null,
  },
  {
    id: "folder-2",
    name: "Marketing Materials",
    type: "Folders",
    owner: "Bob",
    dateModified: "2025-06-20",
    parentId: null,
  },
  {
    id: "file-1",
    name: "Annual Report 2025.pdf",
    type: "PDFs",
    owner: "Alice",
    dateModified: "2025-07-10",
    fileSize: "5.2 MB",
    parentId: null,
  },
  {
    id: "file-2",
    name: "Onboarding Video.mp4",
    type: "Videos",
    owner: "Charlie",
    dateModified: "2025-05-01",
    fileSize: "128 MB",
    parentId: null,
  },

  // --- Items inside "Project Alpha" (parentId: "folder-1") ---
  {
    id: "folder-3",
    name: "Design Assets",
    type: "Folders",
    owner: "Alice",
    dateModified: "2025-07-16",
    parentId: "folder-1",
  },
  {
    id: "file-3",
    name: "Meeting Notes - July.docx",
    type: "Documents",
    owner: "Alice",
    dateModified: "2025-07-15",
    fileSize: "120 KB",
    parentId: "folder-1",
  },
  {
    id: "file-4",
    name: "Budget Q3.xlsx",
    type: "Spreadsheets",
    owner: "Bob",
    dateModified: "2025-07-14",
    fileSize: "78 KB",
    parentId: "folder-1",
  },

  // --- Items inside "Design Assets" (parentId: "folder-3") ---
  {
    id: "file-5",
    name: "Logo_Final_v3.svg",
    type: "Photos & images",
    owner: "Alice",
    dateModified: "2025-07-16",
    fileSize: "1.1 MB",
    parentId: "folder-3",
  },
  {
    id: "file-6",
    name: "Brand Guidelines.pdf",
    type: "PDFs",
    owner: "Alice",
    dateModified: "2025-07-15",
    fileSize: "3.4 MB",
    parentId: "folder-3",
  },
   {
    id: "folder-4",
    name: "📸 Media Library",
    type: "Folders",
    owner: "Diana",
    dateModified: "2025-06-10",
    parentId: null,
  },
  {
    id: "folder-5",
    name: "Client Work",
    type: "Folders",
    owner: "Eve",
    dateModified: "2025-07-01",
    parentId: null,
  },
  {
    id: "file-7",
    name: "Invoice_July_2025.pdf",
    type: "PDFs",
    owner: "Eve",
    dateModified: "2025-07-02",
    fileSize: "320 KB",
    parentId: null,
  },
  {
    id: "file-8",
    name: "Product Demo.mov",
    type: "Videos",
    owner: "Frank",
    dateModified: "2025-06-15",
    fileSize: "256 MB",
    parentId: null,
  },

  // --- Media Library Content (folder-4) ---
  {
    id: "file-9",
    name: "Team_Photo.jpg",
    type: "Photos & images",
    owner: "Diana",
    dateModified: "2025-06-09",
    fileSize: "4.2 MB",
    parentId: "folder-4",
  },
  {
    id: "file-10",
    name: "Background_Music.mp3",
    type: "Audio",
    owner: "Diana",
    dateModified: "2025-06-08",
    fileSize: "6.1 MB",
    parentId: "folder-4",
  },
  {
    id: "file-11",
    name: "Intro_Animation.mp4",
    type: "Videos",
    owner: "Diana",
    dateModified: "2025-06-07",
    fileSize: "47 MB",
    parentId: "folder-4",
  },

  // --- Client Work (folder-5) ---
  {
    id: "folder-6",
    name: "Client A",
    type: "Folders",
    owner: "Eve",
    dateModified: "2025-07-01",
    parentId: "folder-5",
  },
  {
    id: "folder-7",
    name: "Client B",
    type: "Folders",
    owner: "Eve",
    dateModified: "2025-06-28",
    parentId: "folder-5",
  },

  // --- Files under Client A ---
  {
    id: "file-12",
    name: "Proposal_ClientA.docx",
    type: "Documents",
    owner: "Eve",
    dateModified: "2025-06-30",
    fileSize: "230 KB",
    parentId: "folder-6",
  },
  {
    id: "file-13",
    name: "Wireframe_ClientA.pdf",
    type: "PDFs",
    owner: "Eve",
    dateModified: "2025-06-29",
    fileSize: "1.8 MB",
    parentId: "folder-6",
  },

  // --- Files under Client B ---
  {
    id: "file-14",
    name: "Contract_ClientB.pdf",
    type: "PDFs",
    owner: "Eve",
    dateModified: "2025-06-27",
    fileSize: "600 KB",
    parentId: "folder-7",
  },
  {
    id: "file-15",
    name: "UX_Notes_ClientB.docx",
    type: "Documents",
    owner: "Eve",
    dateModified: "2025-06-26",
    fileSize: "150 KB",
    parentId: "folder-7",
  },

  // --- Additional Files & Folders ---
  {
    id: "folder-8",
    name: "📂 Archives",
    type: "Folders",
    owner: "Charlie",
    dateModified: "2025-04-10",
    parentId: null,
  },
  {
    id: "file-16",
    name: "2019_Reports.zip",
    type: "PDFs",
    owner: "Charlie",
    dateModified: "2025-04-09",
    fileSize: "12 MB",
    parentId: "folder-8",
  },
  {
    id: "file-17",
    name: "Screenshots_2020.zip",
    type: "PDFs",
    owner: "Charlie",
    dateModified: "2025-04-08",
    fileSize: "28 MB",
    parentId: "folder-8",
  },

  // --- Add Items to Design Assets Again ---
  {
    id: "file-18",
    name: "SocialMediaIcons.png",
    type: "Photos & images",
    owner: "Alice",
    dateModified: "2025-07-17",
    fileSize: "2.3 MB",
    parentId: "folder-3",
  },
  {
    id: "file-19",
    name: "UI_Design_Sketch.fig",
    type: "PDFs",
    owner: "Alice",
    dateModified: "2025-07-17",
    fileSize: "5.6 MB",
    parentId: "folder-3",
  },

  // --- More Documents ---
  {
    id: "file-20",
    name: "Meeting Minutes 2025-06-01.docx",
    type: "Documents",
    owner: "Bob",
    dateModified: "2025-06-01",
    fileSize: "108 KB",
    parentId: null,
  },
  {
    id: "file-21",
    name: "Growth_Plan.xlsx",
    type: "Spreadsheets",
    owner: "Charlie",
    dateModified: "2025-05-25",
    fileSize: "88 KB",
    parentId: null,
  },
  {
    id: "file-22",
    name: "WelcomeGuide.pptx",
    type: "Presentations",
    owner: "Frank",
    dateModified: "2025-06-18",
    fileSize: "1.5 MB",
    parentId: null,
  },
  {
    id: "file-23",
    name: "StrategyOverview_2025.pptx",
    type: "Presentations",
    owner: "Frank",
    dateModified: "2025-06-20",
    fileSize: "2.1 MB",
    parentId: null,
  },

  // --- Extra Media ---
  {
    id: "file-24",
    name: "Podcast_Episode_01.mp3",
    type: "Audio",
    owner: "Diana",
    dateModified: "2025-06-12",
    fileSize: "34 MB",
    parentId: "folder-4",
  },
  {
    id: "file-25",
    name: "Launch_Trailer.mp4",
    type: "Videos",
    owner: "Frank",
    dateModified: "2025-07-01",
    fileSize: "64 MB",
    parentId: null,
  },
  {
    id: "file-26",
    name: "TeamBudget2025.xlsx",
    type: "Spreadsheets",
    owner: "Bob",
    dateModified: "2025-07-05",
    fileSize: "140 KB",
    parentId: "folder-1",
  },
  {
    id: "file-27",
    name: "Q2-Review.pdf",
    type: "PDFs",
    owner: "Charlie",
    dateModified: "2025-06-30",
    fileSize: "850 KB",
    parentId: "folder-1",
  },
  {
    id: "file-28",
    name: "FAQ.docx",
    type: "Documents",
    owner: "Bob",
    dateModified: "2025-06-25",
    fileSize: "78 KB",
    parentId: "folder-1",
  },
  {
    id: "file-29",
    name: "Roadmap_2026.pdf",
    type: "PDFs",
    owner: "Alice",
    dateModified: "2025-07-18",
    fileSize: "900 KB",
    parentId: null,
  },
  {
    id: "file-30",
    name: "TempBackup_2025.zip",
    type: "PDFs",
    owner: "Charlie",
    dateModified: "2025-07-19",
    fileSize: "17 MB",
    parentId: "folder-8",
  }
];

export const otherAccounts: Account[] = [
  { name: "Atharv Dewangan", email: "atharv.codes04@gmail.com", avatar: "🏕️" },
  {
    name: "Atharv",
    email: "atharvdewanganakd298suncity@gmail.com",
    avatar: "🎵",
  },
  {
    name: "Atharv Dewangan 22BIT0033",
    email: "atharv.dewangan2022@vitstudent.ac.in",
    avatar: "A",
  },
];
